<section class="portada">
		<div class="portada-container">
			<img class="portada-container-logo" src="./public/img/logo1.jpg" alt="">
			<p class="portada-container-subTituloA">Bienvenidos a Digimart</p>
			<p class="portada-container-subTituloB">aquí podrás aprender Marketing Digital Práctico desde tu puesto</p>
			<h1 class="portada-container-titulo">Soy Gerente</h1>
			<button class="portada-container-btn">¡Quiero Registrarme!</button>
		</div>
	</section>
	<header class="menu">
		<nav class="menu-nav">
			<ul class="menu-nav-fixed">
			  <li><img logo" class="image" src="./public/img/logo.png" alt="">	</li>
			  <li>Quienes Somos</a></li>
			  <li>TALLERES</a></li>
			  <li>Registro</a></li>
			  <li>Contactanos</a> </li>
			  <li><button>INSCRIPCIONES</button></li>
			</ul>
		</nav>
	</header>
	<section class="portada2">
		<button class="portada2-btn2">Deja tus datos para el próximo taller</button>
	</section>
	<section class="contenedor">
		<img class="contenedor-picture-a" src="./public/img/natali.jpg" alt="" >
		<div class="contenedor-introduccion">
		<h5 class="contenedor-introduccion-subtitulo">Artesania</h5>
			<p class="contenedor-introduccion-texto-a">It is a long established fact that a reader will be distracted by the readable
			content of a page when looking at its layout. The point of using Lorem Ipsum is
			that it has a more-or-less normal distribution of letters, as opposed to using
			'Content here, content here', making it look like readable English. Many desktop
			publishing packages and web page editors now use Lorem Ipsum as their default
			model text, and a search for 'lorem ipsum'.</p>
		</div>
	</section>
	<section class="contenedor">
		<img class="contenedor-picture-b" src="./public/img/kene.jpg" alt="" >
		<div class="contenedor-introduccion-a">
			<h5 class="contenedor-introduccion-a-subTitulo-b">Kéne</h5>
			<p class="contenedor-introduccion-a-texto-b">It is a long established fact that a reader will be distracted by the readable
			content of a page when looking at its layout. The point of using Lorem Ipsum is
			that it has a more-or-less normal distribution of letters, as opposed to using
			'Content here, content here', making it look like readable English. Many desktop
			publishing packages and web page editors now use Lorem Ipsum as their default
			model text, and a search for 'lorem ipsum'.</p>
		</div>
	</section>
	<section class="contenedor">
		<img class="contenedor-picture-a" src="./public/img/tragos.jpg" alt="">
		<div class="contenedor-introduccion-c">
			<h5 class="contenedor-introduccion-c-subtitulo-c">Principios</h5>
			<p class="contenedor-introduccion-c-texto-a">It is a long established fact that a reader will be distracted by the readable
			content of a page when looking at its layout. The point of using Lorem Ipsum is
			that it has a more-or-less normal distribution of letters, as opposed to using
			'Content here, content here', making it look like readable English. Many desktop
			publishing packages and web page editors now use Lorem Ipsum as their default
			model text, and a search for 'lorem ipsum'.</p>
		</div>
	</section>
	<section class="contenedor3">
		<h5 class="contenedor3-subTitulo5">Ellos te hacen vivir la mejor experiencia. </h5>
		<div class="contenedor3-integrantes">
			<div class="contenedor3-integrantes-integrante">
				<img class="contenedor3-integrantes-integrante-imagenes" src="./public/img/roldan.jpg" alt="">
					<p class="contenedor3-integrantes-integrante-descripcion">It is a long established fact that a reader will be
					distracted by the readable content of a page when
					looking at its layout. The point of using Lorem
					Ipsum he point of using.</p>
					<div class="contenedor3-integrantes-integrante-opcion">
						<button class="contenedor3-integrantes-integrante-opcion-btn6">Ziggy Stardust</button>
						<button class="contenedor3-integrantes-integrante-opcion-btn7">David Bowie</button>
					</div>
			</div>
			<div class="contenedor3-integrantes-integrante">
				<img class="contenedor3-integrantes-integrante-imagenes" src="./public/img/tita.jpg" alt="">
				<p class="contenedor3-integrantes-integrante-descripcion">
					It is a long established fact that a reader will be
					distracted by the readable content of a page when
					looking at its layout. The point of using Lorem
					Ipsum he point of using.</p>
					<div class="contenedor3-integrantes-integrante-opcion">
						<button class="contenedor3-integrantes-integrante-opcion-btn6">Ziggy Stardust</button>
						<button class="contenedor3-integrantes-integrante-opcion-btn7">David Bowie</button>
					</div>
			</div>
			<div class="contenedor3-integrantes-integrante">
				<img class="contenedor3-integrantes-integrante-imagenes" src="./public/img/niña.jpg" alt="">
				<p class="contenedor3-integrantes-integrante-descripcion">
					It is a long established fact that a reader will be
					distracted by the readable content of a page when
					looking at its layout. The point of using Lorem
					Ipsum he point of using..</p>
					<div class="contenedor3-integrantes-integrante-opcion">
						<button class="contenedor3-integrantes-integrante-opcion-btn6">Ziggy Stardust</button>
						<button class="contenedor3-integrantes-integrante-opcion-btn7">David Bowie</button>
					</div>
			</div>
		</div>
	</section>
	<div class="barra">
		<h4 class="barra-txt">Únete a nosotros y forma parte de esta experiencia única</h4>
		<button class="barra-btn8">Registrate Ahora</button>
	</div>
	<section class="contenido">
		<h4 class="contenido-title">Estos son los talleres que tenemos para ti</h4>
		<article class="contenido-articulos">
			<div class="contenido-articulos-picture-c">
				<img src="./public/img/niña-casa.jpg" alt="">
			</div>
			<div class="contenido-articulos-texto-c">
				<h6 class="contenido-articulos-texto-c-titulo-C">Arte en la sangre</h6>
				<p class="contenido-articulos-texto-c-parrafoIzquierda">It is a long established fact that a reader will be distracted by the readable
				content of a page when looking at its layout. The point of using Lorem Ipsum is
				that it has a more-or-less normal distribution of letters, as opposed to using
				'Content here, content here', making it look like readable English. Many desktop
				publishing packages and web page editors now use Lorem Ipsum as their default
				model text, and a search for 'lorem ipsum'.</p>
			</div>
		</article>
		<article class="contenido-articulos">
			<div class="contenido-articulos-picture-d">
				<img src="./public/img/madres.jpg" width="600px" height="400px">
			</div>
			<div class="contenido-articulos-texto-d">
				<h6 class="contenido-articulos-texto-c-titulo-d">Estadística Digital</h6>
				<p class="contenido-articulos-texto-c-parrafoIzquierda">It is a long established fact that a reader will be distracted by the readable
				content of a page when looking at its layout. The point of using Lorem Ipsum is
				that it has a more-or-less normal distribution of letters, as opposed to using
				'Content here, content here', making it look like readable English. Many desktop
				publishing packages and web page editors now use Lorem Ipsum as their default
				model text, and a search for 'lorem ipsum'.</p>
			</div>
		</article>
		<article class="contenido-articulos">
			<div class="contenido-articulos-picture-c">
				<img src="./public/img/madre-artesana.jpg" width="600px" height="400px">
			</div>
			<div class="contenido-articulos-texto-c">
				<h6 class="contenido-articulos-texto-c-titulo-C">Estrategia Digital</h6>
				<p class="contenido-articulos-texto-c-parrafoIzquierda">It is a long established fact that a reader will be distracted by the readable
				content of a page when looking at its layout. The point of using Lorem Ipsum is
				that it has a more-or-less normal distribution of letters, as opposed to using
				'Content here, content here', making it look like readable English. Many desktop
				publishing packages and web page editors now use Lorem Ipsum as their default
				model text, and a search for 'lorem ipsum'.</p>
			</div>
		</article>
	</section>
	<div class="barra-2">
		<h3 class="barra-2-txt1">¡NO ESPERES MÁS!</h3>
		<h4 class="barra-2-txt2">Experimenta, Reflexiona, Conoce y Aplica</h4>
		<button class="barra-2-btn9">Registrate Ahora</button>
	</div>
	<section class="portada3">
		<img class="portada3-imgMundo" src="./public/img/mundo1.png" alt="">
		<h2 class="portada3-titulo3">¡Llego el Momento! <br>de Aprender</h2>
		<p class="portada3-parrafo">Antes de empezar este fabuloso viaje al<br>
		aprendizaje del marketing digital debes tener<br>
		algunos conocimientos básicos de</p>
		<button class="portada3-btn10">¡LEER AHORA!</button>
	</section>
	<!--<section class="programas">
			<h3 class="programas-subTitulo6">Estos son los talleres que tenemos para ti</h3>
		<article class="programas-articulo">
			<div class="programas-articulo-talleres">
				<img class="programas-articulo-talleres-image" src="./public/img/niña.png" alt="">
				<h6 class="programas-articulo-talleres-titulo-a">Creatividad Metropolitana</h6>
				<p class="programas-articulo-talleres-parrago-a">t is a long established fact that a reader
				content of a page when looking at its
				layout. The point of using Lorem Ipsum
				making</p>
				<button class="programas-articulo-talleres-btn-a">Leer más</button>
			</div>
		</article>
		<article class="programas-articulo">
			<div class="programas-articulo-talleres">
				<img class="programas-articulo-talleres-image" src="./public/img/reloj.png" alt="">
				<h6 class="programas-articulo-talleres-titulo-a">Creatividad Metropolitana</h6>
				<p class="programas-articulo-talleres-parrago-a">t is a long established fact that a reader
				content of a page when looking at its
				layout. The point of using Lorem Ipsum
				making</p>
				<button class="programas-articulo-talleres-btn-a">Leer más</button>
			</div>
		</article>
		<article class="programas-articulo">
			<div class="programas-articulo-talleres">
				<img class="programas-articulo-talleres-image" src="./public/img/creatividad.png" alt="">
				<h6 class="programas-articulo-talleres-titulo-a">Creatividad Metropolitana</h6>
				<p class="programas-articulo-talleres-parrago-a">t is a long established fact that a reader
				content of a page when looking at its
				layout. The point of using Lorem Ipsum
				making</p>
				<button class="programas-articulo-talleres-btn-a">Leer más</button>
			</div>
		</article>
	</section> <--></-->
	<section class="portada4">
		<div class="portada4-texto-1">
			<h1 class="portada4-texto-1-bienvenida">¡Hola!</h1>
			<p class="portada4-texto-1-parrafo-b">Ahora es momento de una experiencia de aprendizaje diferente aquí podrás<br>
			Experimentar, Reflexionar, Conocer y Aplicar técnicas de Marketing Digital</p>
			<h2 class="portada4-texto-1-txt-a">Estoy listo para registrarme</h2>
			<button class="portada4-texto-1-btn-b">star</button>
			<p class="portada4-texto-1-palabra">press ENTER</p>
		</div>
	</section>
	<footer>
		<div class="footer">
			<ul class="footer-listas">
				<li class="footer-listas-datos">(511) 947 561 509</li>
				<li class="footer-listas-datos">mpalacios@uniclick.com.pe</li>
				<li class="footer-listas-datos">Jr. Artesanos - Cantagallo </li>
			</ul>
			<ul class="footer-listas-a">
				<li class="footer-listas-a-logos"> <img src="./public/img/facebook.png" alt="">   </li>
				<li class="footer-listas-a-logos"> <img src="./public/img/google.png" alt="">   </li>
				<li class="footer-listas-a-logos"> <img src="./public/img/wsp.png" alt="">   </li>
				<li class="footer-listas-a-logos"> <img src="./public/img/youtube.png" alt="">   </li>
			</ul>
			<ul class="footer-listas-b">
				<li class="footer-listas-b-cursos">EXPERIENCIA DIGISMART |</li>
				<li class="footer-listas-b-cursos">TALLERES |</li>
				<li class="footer-listas-b-cursos">APRENDE |</li>
				<li class="footer-listas-b-cursos">ARTÍCULOS |</li>
				<li class="footer-listas-b-cursos">INSCRIPCIONES</li>
			</ul>
		</div>
		<img class="linea" src="./public/img/linea.png" alt="">
	</footer>