<div class="row">
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-sun-flower">
			<h4>Usuarios</h4>
			<p><a href="<?php echo $this->url("administrador"); ?>">Ver</a></p>			
			<p><a href="<?php echo $this->url("administrador"); ?>">Carga masiva</a></p>
			<p><a href="<?php echo $this->url("administrador");?>">&nbsp;</a></p>
			<i class="glyphicon glyphicon-user"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-wet-asphalt">
			<h4>Administrador</h4>
			<p><a href="<?php echo $this->url("administrador"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("administrador",array('action'=>'agregar-administrador'));?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("administrador"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-child"></i>
		</div>
	</div>	
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-peter-river">
			<h4>Publicaciones</h4>
			<p><a href="<?php echo $this->url("administrador"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("administrador", array('action' => 'agregar-docente')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("administrador"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-male"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-nephritis">
			<h4>Cursos</h4>
			<p><a href="<?php echo $this->url("administrador"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("administrador", array('action' => 'agregar-estudiante')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("administrador"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-group"></i>
		</div>
	</div>	
</div>










